# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.provider :virtualbox do |vb|
      vb.customize [
        "modifyvm", :id,
        "--paravirtprovider", "minimal",
        "--cpus", "2"
      ]
  end	
  config.vm.define "server" do |server|
    server.vm.box = "ubuntu/focal64"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.12"
    server.vm.provision "shell", path: "server.sh"
  end

  config.vm.define "client" do |client|
    client.vm.box = "ubuntu/focal64"
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.56.13"
    client.vm.provision "shell", path: "client.sh"
  end
end