{{- if .Values.wordpress.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-wordpress-hpa
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-wordpress
  minReplicas: {{ .Values.wordpress.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.wordpress.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.wordpress.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}